d = 
	{  
	   "title": "Nerd Quiz 2017 reloaded",
	   "intro":"NERD-QUIZ INTRO.mp4",
	   "categories":  
		  [
		  {  
			 "category": "Klassiker",
			 "questions": [  
				{  
				   "question":"1.1.jpg",
				   "answers":[  
						"Loesungen/1.1.1.jpg",
				"Loesungen/1.1.2.jpg",
				"Loesungen/1.1.3.jpg",
				"Loesungen/1.1.4.jpg",
				"Loesungen/1.1.5.jpg"
				   ]
				},
				{  
				   "question":"1.2.jpg",
				   "answers":[  
					  "Loesungen/1.2.jpg"
				   ]
				},
				{  
				   "question":"1.3.jpg",
				   "answers":[  
					  "Loesungen/1.3.jpg"
				   ]
				},
				{  
				   "question":"1.4.jpg",
				   "answers":[  
					  "Loesungen/1.4.jpg"
				   ]
				},
				{  
				   "question":"1.5.jpg",
				   "answers":[  
					  "Loesungen/1.5.1.jpg",
			  "Loesungen/1.5.2.jpg"
				   ]
				},
				{  
				   "question":"1.6.jpg",
				   "answers":[  
					  "Loesungen/1.6.jpg",
				   ]
				}
			 
			 ]
		},

		{"category": "Shooter",
		"questions":[
			{
			"question":"2.1.jpg",
			"answers":[
			  "Loesungen/2.1.jpg"
			]
			},
			{
			"question":"2.2.jpg",
			"answers":[
			  "Loesungen/2.2.jpg"
			]
			},
			{
			"question":"2.3.jpg",
			"answers":[
			  "Loesungen/2.3.jpg"
			]
			},			    {
			"question":"2.4.jpg",
			"answers":[
			  "Loesungen/2.4.jpg"
			]
			},			    {
			"question":"2.5.jpg",
			"answers":[
			  "Loesungen/2.5.jpg"
			]
			},			    {
			"question":"2.6.jpg",
			"answers":[
			  "Loesungen/2.6.mp4"
			]
			},
		]},
		{"category": "Mystery",
		"questions":[
			{
			"question":"3.1.jpg",
			"answers":[
			  "Loesungen/3.1.jpg"
			]
			},
			{
			"question":"3.2.jpg",
			"answers":[
			  "Loesungen/3.2.mp4"
			]
			},
			{
			"question":"3.3.jpg",
			"answers":[
			  "Loesungen/3.3.jpg"
			]
			},
			{
			"question":"3.4.jpg",
			"answers":[
			  "Loesungen/3.4.jpg"
			]
			},
			{
			"question":"3.5.jpg",
			"answers":[
			  "Loesungen/3.5.jpg"
			]
			},
			{
			"question":"3.6.jpg",
			"answers":[
			  "Loesungen/3.6.jpg"
			]
			},

		]},
		{
			"category": "Filme und Serien",
			"questions": [
				{
					"question":"4.1.jpg",
					"answers":[
						"Loesungen/4.1.jpg"
					]
				},
				{
					"question":"4.2.jpg",
					"answers":[
						"Loesungen/4.2.mp4"
					]
				},
				{
					"question":"4.3.jpg",
					"answers":[
						"Loesungen/4.3.mp4"
					]
				},
				{
					"question":"4.4.jpg",
					"answers":[
						"Loesungen/4.4.mp4"
					]
				},
				{
					"question":"4.5.jpg",
					"answers":[
						"Loesungen/4.5.mp4"
					]
				},
{
					"question":"4.6.mp4",
					"answers":[
						"Loesungen/4.6.jpg"
					]
				},
			]
		}
			

		],
	   "grouprounds": [
		   {
				"title": "Gruppenrunde 1",
				"questions":
			   [
				   {
					   "question":"4.5.jpg",
					   "questionUnblur": true,
					   "answers":[
					   ]
				   },
				   {
					   "question":"G1.2.mp4",
					   "answers":[
					   ]
				   },
				   {
					   "question":"G1.3.mp4",
					   "answers":[
					   ]
				   },
				   {
					   "question":"G1.4.mp4",
					   "answers":[
					   ]
				   },
				   {
						"question":"G1.5.mp4",
					   "answers":[
					   ]
				   },
				   {
					   "question":"G1.6.mp4",
					   "answers":[
					   ]
				   },
				   {
					   "question":"G1.7.mp4",
					   "answers":[
					   ]
				   },
				   {
					   "question":"G1.8.mp4",
					   "answers":[
					   ]
				   },
				   {
					   "question":"G1.9.mp4",
					   "answers":[
					   ]
				   },
				   {
					   "question":"G1.10.mp4",
					   "answers":[
					   ]
				   },
			   ]
		   },
		   {
				"title": "Gruppenrunde 2",
				"questions":
			   [
				   {
					   "question":"G2.1.jpg",
					   "answers":["Loesungen/G2.1.jpg"
					   ]
				   },
				   {
					   "question":"G2.2.jpg",
					   "answers":["Loesungen/G2.2.jpg"
					   ]
				   },
				   {
					   "question":"G2.3.jpg",
					   "answers":["Loesungen/G2.3.jpg"
					   ]
				   },
				   {
					   "question":"G2.4.jpg",
					   "answers":["Loesungen/G2.4.jpg"
					   ]
				   },
				   {
					   "question":"G2.5.jpg",
					   "answers":["Loesungen/G2.5.jpg"
					   ]
				   },
				   {
					   "question":"G2.6.jpg",
					   "answers":["Loesungen/G2.6.jpg"
					   ]
				   },
				   {
					   "question":"G2.7.jpg",
					   "answers":["Loesungen/G2.7.jpg"
					   ]
				   },
				   {
					   "question":"G2.8.jpg",
					   "answers":["Loesungen/G2.8.jpg"
					   ]
				   },
				   {
					   "question":"G2.9.jpg",
					   "answers":["Loesungen/G2.9.jpg"
					   ]
				   },
				   {
					   "question":"G2.10.jpg",
					   "answers":["Loesungen/G2.10.jpg"
					   ]
				   },
			   ]               
		   },
		   {
				"title": "Stichfragen",
				"questions":
			   [
				   {
					   "question":"S1.jpg",
					   "answers":[
						   "Loesungen/S1.jpg"
					   ]
				   },
				   {
					   "question":"S2.jpg",
					   "answers":[
						   "Loesungen/S2.jpg"
					   ]
				   },
				   {
					   "question":"S3.jpg",
					   "answers":[
						   "Loesungen/S3.jpg"
					   ]
				   },
			   ]               
		   },
		   
	   ]
	}
